version: '3.6'

services:

  node-prod:
    build:
      context: ./services/node
      dockerfile: Dockerfile-prod
    volumes:
      - './services/node:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - NODE_ENV=production

  client-prod:
    build:
      context: ./services/client
      dockerfile: Dockerfile-prod
    environment:
      - NODE_ENV=production
    depends_on:
      - node-prod

  nginx-prod:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - node-prod
      - client-prod