version: "3.6"

services:

  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 5000:5000
    volumes:
      - './server/:/app'
      
  client:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    volumes:
      - "./client:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - client
      - server
