version: "3.6"

services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile-dev
    volumes:
      - "./node:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      - NODE_ENV=development
      - NODE_PORT=3001
      - CHOKIDAR_USEPOLLING=true
      - COINGECKO_CACHE_TIMEOUT=60
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017/
    ports:
      - 9229:9229

  client:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    volumes:
      - "./client:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - node

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - node
      - client