FROM mcr.microsoft.com/dotnet/core/sdk:3.1

WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

ENV ASPNETCORE_ENVIRONMENT=production

COPY . ./
RUN dotnet publish -c Release -o out

ENTRYPOINT dotnet run