FROM node:latest

WORKDIR usr/src/app

COPY package.json /usr/src/app/package.json
COPY package-lock.json /usr/src/app/package-lock.json

RUN npm install
RUN npm install -g nodemon
RUN npm install -g node-inspect

CMD ["nodemon", "--inspect=0.0.0.0", "./server.js"]